### ISSUE TITLE
"If it is unambiguously CommonJS"

### ISSUE THREAD

**Issue by devsnek** [GeoffreyBooth/node-esm-entry-points-proposal#2] opened 2019-02-06 21:23 UTC
This is a very specific thing to be able to test for statically. If there is such an auto mode, it might be better to treat "not esm" as cjs. For example, a minifier might collapse require calls.

**Comment by SMotaal** [comment] 2019-02-07 08:17
I was planning to continue work on this next week: http://experimental.smotaal.io/modules/parsing#considerations

But until then, I will hash out what it takes (imho) to detect syntax features:

1. An efficient tokenizer able to identify limited keywords (correctly)
   - It properly handles strings, regexp, and comments
   - It glosses over syntax it does not know (future-proof)
   - It detects certain token types (TBD)
   - It stops as soon as a rule is satisfied (below).

2. The token iterator looks for the first non-competing discriminator.
   - Top-level static `import` or `export` (`return 'esm';`)
   - Any reference to `import.…` or `import.meta.…` (`return 'esm';`)
   - Top-level `module.…`, `module.exports.…` or `exports.…` assignment (`return 'cjs';`)

**Note** The following is just theoretical, CJS folks should chime in. I don't like it yet, and prefer to stick with the above and determine which mode to default to based on flags, configs... etc. which should already be known.

3. The token iterator optionally tracks competing discriminators.
   - Top-level starts with `(function…` (`maybe.umd++; continue;`)
     - Can still be ESM or CJS
   - Call to `require(…)` or `require.resolve(…)` (`maybe.cjs++; continue;`)
     - May ESM with top-level import in end (yuck, but not illegal) 
   - RHS Reference to `__dirname` or `__filename` (`maybe.cjs++; continue;`)
   - Shadowing assignment to any of the above identifiers (`--` respectively)

**Minified Code**

I think it is easy to identify minified code because it often starts with a very long line involving several occurrences of the keyword `function` and some of the identifiers `define`, `require`, `module`, `exports`… etc.

The problem is, when minified code is wrapped into an ESM module, nothing says a person cannot do that.

**Comment by SMotaal** [comment] 2019-02-07 10:16
Completely separate from any parsing, "default" as CJS when there is no other thing to work on is in my opinion the expected behaviour for Node.js.

**Edit**: Our effort should allow simple and explicit ways for a user to tell Node.js to "default" to ESM if that is what they expect. Not force them to need to use custom loaders or need a `package.json`.

**Comment by SMotaal** [comment] 2019-02-07 10:35
I was planning to continue work on this next week: http://experimental.smotaal.io/modules/parsing#considerations

But until then, I will hash out what it takes (imho) to detect syntax features:

1. An efficient tokenizer able to identify limited keywords (correctly)
   - It properly handles strings, regexp, and comments
   - It glosses over syntax it does not know (future-proof)
   - It detects certain token types (TBD)
   - It stops as soon as a rule is satisfied (below).

2. The token iterator looks for the first non-competing discriminator.
   - Top-level static `import` or `export` (`return 'esm';`)
   - Any reference to `import.…` or `import.meta.…` (`return 'esm';`)
   - Top-level `module.…`, `module.exports.…` or `exports.…` assignment (`return 'cjs';`)

**Note** The following is just theoretical, CJS folks should chime in. I don't like it yet, and prefer to stick with the above and determine which mode to default to based on flags, configs... etc. which should already be known.

3. The token iterator optionally tracks competing discriminators.
   - Top-level starts with `(function…` (`maybe.umd++; continue;`)
     - Can still be ESM or CJS
   - Call to `require(…)` or `require.resolve(…)` (`maybe.cjs++; continue;`)
     - May ESM with top-level import in end (yuck, but not illegal) 
   - RHS Reference to `__dirname` or `__filename` (`maybe.cjs++; continue;`)
   - Shadowing assignment to any of the above identifiers (`--` respectively)

**Minified Code**

I think it is easy to identify minified code because it often starts with a very long line involving several occurrences of the keyword `function` and some of the identifiers `define`, `require`, `module`, `exports`… etc.

The problem is, when minified code is wrapped into an ESM module, nothing says a person cannot do that.

**Comment by GeoffreyBooth** [comment] 2019-02-07 23:50
I wrote the proposal to not rely on being able to accurately detect CommonJS. If what @SMotaal proposes above works, it’s an option, but the simpler version is the “evaluate as ESM, else evaluate as CommonJS” algorithm that I wrote in the proposal as the second option. That’s what was explored by @zenparsing in https://github.com/nodejs/modules/issues/254.

Whether ambiguous (could be ESM or CommonJS) code is run as ESM or CommonJS is up for debate, but I’m assuming that we probably go with the latter (eval ESM/eval CJS) algorithm in which case there’s a performance motivation to prefer ESM evaluation for ambiguous files. If we make detection the _default,_ not something to be opted into, then we would need to choose between running ambiguous code as CommonJS or instead accepting a breaking change in that ambiguous code would run as ESM. Ambiguous code is rare—most real-world Node programs `require` or `import` _something,_ even if only core modules—so it wouldn’t be a huge breaking change, but it would be one.

Also note that ambiguous code running as ESM versus CommonJS doesn’t have much practical difference beyond that the latter runs in strict mode, root-level `this` references something different, and a few other minor differences that shouldn’t matter in most code. Running ambiguous code as ESM instead of CommonJS won’t make a difference in most real-world code; but again, this only matters if we make detection automatic, rather than something to be opted into.

So anyway, I’m not sure what’s being asked here. Perhaps I should rephrase something in the proposal? I’m assuming that it’s not possible to for-sure detect either ESM or CommonJS, in which case we have what I’m calling ambiguous code, that I’m proposing gets executed as ESM. The proposal isn’t relying on perfect accuracy in its detection, as it defines a behavior to happen for code that can’t be unambiguously detected as either ESM or as CommonJS.

**Comment by devsnek** [comment] 2019-02-08 00:27
@GeoffreyBooth i interpreted the proposal as saying cjs would only be selected by auto mode if it could be explicitly detected, if that's not the case this can be closed.

**Comment by GeoffreyBooth** [comment] 2019-02-08 00:48
> i interpreted the proposal as saying cjs would only be selected by auto mode if it could be explicitly detected

That might be the case under the parsing algorithm, that @SMotaal is working on. I’ll leave him to respond to that.

Under the “eval as ESM, else eval as CJS” algorithm, there is no explicit detection for CommonJS. Node simply tries to run the initial entry point as ESM, and if it succeeds, that’s it. Otherwise it tries again, running the initial entry point as CommonJS. So CommonJS is the fallback, only executed in the event that ESM execution fails. It’s the lack of success at execution under ESM that triggers the CommonJS evaluation, not anything parsed from in the code itself.

In bash terms, `node --type=auto app.js` is roughly equivalent to:
```bash
node --type=module app.js || node --type=commonjs app.js
```

**Comment by zenparsing** [comment] 2019-02-08 01:15
@GeoffreyBooth to clarify, in my technique an "ambiguous" target is compiled with the existing CJS loader as usual, and only if if fails with a specific syntax error indicating the presense of import/export declarations does it "fall back" to ESM.

I suspect that you might run into difficulty reliably detecting when "ESM execution fails" due to CJS constructs. Is there a prototype of this behavior?

**Comment by GeoffreyBooth** [comment] 2019-02-08 04:58
> I suspect that you might run into difficulty reliably detecting when "ESM execution fails" due to CJS constructs.

Yes, perhaps. That’s why I was thinking that another option could be simply trying the fallback CJS execution in the event of _any_ error thrown by the ESM execution, though that presents its own issues.

> Is there a prototype of this behavior?

No but @guybedford and @SMotaal are interested in creating one. I suggest you reach out to them.

**Comment by GeoffreyBooth** [comment] 2019-02-10 02:28
> @GeoffreyBooth i interpreted the proposal as saying cjs would only be selected by auto mode if it could be explicitly detected, if that’s not the case this can be closed.

Unless anyone objects I think I’m going to close this issue, as I feel like whatever implementation we end up with is unlikely to be trying to explicitly detect CommonJS, for the reasons mentioned above. I’m sure there will be plenty more discussion around the detection algorithm once it’s written (or once a few variations are written) and we should organize that discussion into distinct threads.

**Closed as completed by GeoffreyBooth** 2019-02-10 02:28 UTC
